[package]
name = "vogelsang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
  "erfurt",
  "degiro",
  "qualsdorf",
]

[dependencies]
erfurt = { path = "erfurt" } 
degiro = { path = "degiro" } 
qualsdorf = { path = "qualsdorf" } 
async-trait = "0.1.57"
color-eyre = "0.6.2"
statrs = "0.16.0"
tokio = { version = "1.21.1", features = ["rt-multi-thread", "parking_lot"] }
ndarray = "0.15.6"
gcp_auth = "0.7.3"
google-sheets4 = "4.0.1"
hyper = "0.14.20"
hyper-rustls = "0.23.0"
axum = "0.5.16"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
toml = "0.5.9"
config = "0.13.2"
clap = { version = "4.0.7", features = ["clap_derive", "derive"] }
serde = { version = "1.0.145", features = ["derive"] }
chrono = { version = "0.4.22", features = ["serde"] }
dashmap = "5.4.0"
